version: '3.8'

services:
  nextjs:
    image: portfolio
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
